#!/usr/bin/env zsh
#
# ZPlug + custom scripts

# Profile
# zmodload zsh/zprof

# load zplug if it doesn't exist
source ~/.zplug/init.zsh

# Manage zplug via zplug
# zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug "~/.zsh.d", from:local, use:"init.zsh"

# zplug "chrissicool/zsh-256color"
# zplug "zsh-users/zsh-history-substring-search"
zplug "zdharma-continuum/fast-syntax-highlighting", defer:2
#zplug "zsh-users/zsh-autosuggestions", defer:3

zplug "agkozak/zsh-z"  # 0.1
# zplug "Tarrasch/zsh-bd" # Go back bd
# zplug "supercrabtree/k" # Better ls

zplug "paulirish/git-open", as:plugin

# Version manager
# zplug "asdf-vm/asdf", use:"asdf.sh"

# zplug "postmodern/chruby", use:""

# FZF for history and directories
# zplug "junegunn/fzf", as:command, \
#   hook-build:"./install --bin", \
#   use:"bin/{fzf-tmux,fzf}"

# # # Actually install plugins, prompt user input # 0.2
# if ! zplug check --verbose; then
#     printf "Install zplug plugins? [y/N]: "
#     if read -q; then
#; zplug install
#     fi
# fi

zplug load

export BREW_PREFIX=$(brew --prefix)

# Add version managers
# . /usr/local/opt/asdf/libexec/asdf.sh
. $BREW_PREFIX/opt/chruby/share/chruby/chruby.sh
. $BREW_PREFIX/opt/chruby/share/chruby/auto.sh

# Add FZF
[ -f ~/.fzf.zsh ] && . ~/.fzf.zsh
# source ~/.config/broot/launcher/bash/br
